# Generated by Django 6.0.2 on 2026-02-22 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_location', models.CharField(blank=True, max_length=150, null=True)),
                ('store_description', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='Store Logo')),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('job_location', models.CharField(blank=True, max_length=150, null=True)),
                ('job_type', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Flexible', 'Flexible')], max_length=20)),
                ('job_description', models.CharField(blank=True, max_length=500, null=True)),
                ('job_requirement', models.CharField(blank=True, max_length=500, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='EmployerApp.employerdb')),
            ],
        ),
    ]
