# Generated by Django 6.0.2 on 2026-03-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployerApp', '0003_applicantrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantrating',
            name='note',
        ),
        migrations.AddField(
            model_name='jobdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='applicantrating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
