# Generated by Django 6.0.2 on 2026-04-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployerApp', '0004_remove_applicantrating_note_jobdb_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdb',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
